return {
	["Small House"] = {
		Name = "Small House",
		Description = "A small house that generates a modest income.",
		Rarity = "Common",
		Size = "4x4",

		Price = 500,
		Income = 10,
		Upgrade = 1,

		BuildTime = 10, -- in seconds
		RequiresRoad = true,
		Offset =  3.125 -- Y offset from ground
	},

	["Medium House"] = {
		Name = "Medium House",
		Description = "-",
		Rarity = "Common",
		Size = "3x3",

		Price = 1500,
		Income = 25,
		Upgrade = 1,

		BuildTime = 30,
		RequiresRoad = true,
		Offset =  3.125
	},

	["Cottage"] = {
		Name = "Cottage",
		Description = "-",
		Rarity = "Uncommon",
		Size = "8x6",

		Price = 2500,
		Income = 50,
		Upgrade = 2,

		BuildTime = 60,
		RequiresRoad = true,
		Offset =  3.125
	},
}
