return {
	["Small House"] = {
		Name = "Small House",
		Description = "A small house that generates a modest income.",
		Price = 10,
		Income = 5,
		Upgrade = 1,

		Offset =  3.125 -- Y offset from ground
	},

	["Medium House"] = {
		Name = "Medium House",
		Description = "A Medium house that generates a modest income.",
		Price = 10,
		Income = 5,
		Upgrade = 2,

		Offset =  3.125 -- Y offset from ground
	},
}
